apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store

spec:
  provider:
    gcpsm:
      projectID: project-18ee516c-a108-431d-a73
      auth:
        workloadIdentity:
          clusterLocation: asia-south1-a
          clusterName: project-18ee516c-a108-431d-a73-gke

          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets