apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: slack-notifications
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 1h
    receivers:
      - name: slack-notifications

        slack_configs:
          - api_url: "replace_with_webhook_url" 
            channel: '#alerts'
            send_resolved: true
type: Opaque