apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: vote
spec:
  # type: LoadBalancer
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 80
  selector:
    app: vote
  
