apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vote-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - vote

  selector:
    matchLabels:
      app: vote

  endpoints:
    - port: http
      path: /metrics
      interval: 15s